---
version: '3.7'
services:

  arxiv2git-py:
    image: x0rzkov/arxiv2git-py:latest
    container_name: arxiv2git-py
    build: ./python
    environment:
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
    - arxiv2git-data:/opt/app/data
    command: ["all"]

  arxiv2git-go:
    image: x0rzkov/arxiv2git-go:latest
    container_name: arxiv2git-go
    build: ./golang
    environment:
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
    - "4242:4242"
    volumes:
    - arxiv2git-data:/opt/app/data
    command: ["all"]

  tor-privoxy:
    container_name: arxiv2git-torprivoxy
    image: dockage/tor-privoxy:latest
    ports:
    - "9050:9050" # Tor proxy
    - "9051:9051" # Tor control port
    - "8118:8118" # Privoxy 

  elasticsearch:
    container_name: arxiv2git-elastic
    #restart: unless-stopped
    #environment:
    #  - ES_JAVA_OPTS=-Xms2g -Xmx2g
    # mem_limit: 4g
    # memswap_limit: 4g
    build:
      context: ./.docker/elasticsearch
      dockerfile: Dockerfile
      args:
        - CEREBRO_VERSION=0.7.2
    entrypoint: /usr/share/elasticsearch/start
    ports:
    - "9200:9200" # Elasticsearch
    - "9000:9000" # Cerebro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      #nofile:
      #  soft: 65536
      #  hard: 65536
    #cap_add:
    #  - IPC_LOCK
    volumes:
    - arxiv2git-esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: arxiv2git-kibana
    ports:
    - 5601:5601

volumes:
  arxiv2git-esdata:
    driver: local
  arxiv2git-data:
    driver: local

networks:
  default:
    external:
      name: arxiv2git
